# Generated by Django 3.2.13 on 2022-07-04 14:47

from django.db import migrations


def populate_providers(apps, schema_editor):
    from providers.models import Provider

    for provider in Provider.PROVIDERS:
        Provider.objects.create(name=provider[0])


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_providers),
    ]
