# Generated by Django 3.2.13 on 2022-06-26 19:28

from django.db import migrations


def populate_currencies(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')

    create_currencies = [
        {
            'code': 'EUR',
            'name': 'Euro',
            'symbol': '€',
        },
        {
            'code': 'CHF',
            'name': 'Swiss franc',
            'symbol': 'Fr',
        },
        {
            'code': 'USD',
            'name': 'Dollar',
            'symbol': '$',
        },
        {
            'code': 'GBP',
            'name': 'Pound sterling',
            'symbol': '£',
        }
    ]

    for currency in create_currencies:
        Currency.objects.create(**currency)


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_currencies),
    ]
