# Generated by Django 3.2.13 on 2022-06-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_populate_currencies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
    ]
